elifaz/newsletter/urls.py
from django.conf.urls import patterns, url
from django.views.generic import ListView
from newsletter.models import Issue
from newsletter.views import *

urlpatterns = patterns(
    '',
    url(r'^$', ListView.as_view(model=Issue), name='issue_list'),
    url(r'^(?P<number>\w+)/$', IssueDetailView.as_view(),
        name="issue_detail"),
    url(r'^(?P<number>\w+)/email/$', IssueDetailEmailView.as_view(),
        name="issue_detail_email"),
)

elifaz/sn/urls.py
from django.conf.urls import patterns, url
from django.views.generic import ListView
from sn.models import Person
from sn.views import *

urlpatterns = patterns(
    '',
    url(r'^$', ListView.as_view(
            queryset=Person.objects.all().order_by('last_name',
                                                   'first_name')),
        name='person_list'),
    url(r'^(?P<slug>\w+)/$', PersonDetailView.as_view(), name="person_detail"),
)

elifaz/newsletter/models.py
#!/usr/bin/python
# coding: latin-1

from django.db import models
from mailsnake import MailSnake
from mailsnake.exceptions import *
from datetime import datetime
from django.template.loader import render_to_string
from django.template import Context
from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.utils import timezone
from elifaz import settings

class Section(models.Model):
    name = models.CharField('nome', max_length=50, unique=True)
    position = models.IntegerField('posizione', blank=True, null=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'sezione'
        verbose_name_plural = 'sezioni'
        ordering = ['position', 'name']

        
class MyMailSnake(MailSnake):
    def __init__(self, apikey):
        super(MyMailSnake, self).__init__(apikey)
        self.apikey = apikey

    def send(self, list_id, email_address, type, opts, content):
        self.listMemberInfo(id=list_id, email_address=email_address)
        return self.campaignSendNow(apikey=self.apikey,
            cid=self.campaignCreate(type=type, options=opts, content=content))


from chances.models import Post

class Issue(models.Model):
    number = models.IntegerField('numero', unique=True)
    start = models.DateTimeField('da')
    end = models.DateTimeField('a')
    last_sent = models.DateTimeField('ultimo invio', null=True)

    def formatted_number(self):
        return "{0:03d}".format(self.number)
    
    def formatted_title(self):
        return 'Newsletter #{0}'.format(self.number) # &#8470;

    def __unicode__(self):
        return "{0}".format(self.formatted_number())

    def get_absolute_url(self):
        return reverse('issue_detail', kwargs={'number': self.number})
    
    def sent(self):
        return self.last_sent != None

    sent.boolean = True
    sent.short_description = 'inviata'

    def opts(self):
        opts = {'list_id': settings.MAILCHIMP_LIST_ID}
        opts['subject']=self.__unicode__() + ' ' + timezone.now().strftime(
            '%d %B %Y, %H.%M.%S')
        opts['from_email']='enricovise@gmail.com'
        opts['from_name']='Mr Enrico Visentini'
        opts['tracking']={'opens': True, 'html_clicks': True,
                          'text_clicks': False}
        opts['authenticate'] = True
        opts['title'] = 'Test ' + timezone.now().strftime('%d %B %Y, %H.%M.%S')
        return opts
        
    def context(self):
        return Context({'issue': self,
                        'post_list': Post.objects.published_range(self.start,
                                                                  self.end)})

    def content(self):
        return {'html': render_to_string('newsletter/issue_detail_email.html',
                                         self.context()),
                'text': 'Plain text: Ecco!',}

    def send(self):
        sent = MyMailSnake(settings.MAILCHIMP_APIKEY).send(
            settings.MAILCHIMP_LIST_ID, 'enricovise@gmail.com', 'regular',
                                                    self.opts(), self.content())
        if sent:
            self.last_sent = timezone.now()
            self.save()
        return sent

    class Meta:
        verbose_name = 'edizione'
        verbose_name_plural = 'edizioni'
        ordering = ['-number']

elifaz/newsletter/views.py
from django.views.generic import DetailView
from newsletter.models import Issue
from chances.models import Post

class IssueDetailView(DetailView):
    model = Issue
    slug_field='number'
    slug_url_kwarg='number'

    def get_context_data(self, **kwargs):
        context = super(IssueDetailView, self).get_context_data(**kwargs)
        context['post_list'] = Post.objects.published_range(self.object.start,
                                                            self.object.end)
        return context

class IssueDetailEmailView(IssueDetailView):
    template_name='newsletter/issue_detail_email.html'

templates/newsletter/content.html
{% regroup post_list by label as section_list %}
{% for section in section_list %}
  <section>
    <h2>{{ section.grouper }}</h2>
    {% for post in section.list %}
      {% include "chances/post_detail.html" %}
    {% endfor %}
  </section>
{% endfor %}

templates/newsletter/heading.html
{{ issue.formatted_title|safe }}
{% include "shared/published_female.html" with date=issue.end %}

templates/newsletter/issue_detail.html
{% extends "shared/base_web.html" %}

{% block title %}{% include "newsletter/title.html" %}{% endblock %}
{% block heading %}{% include "newsletter/heading.html" %}{% endblock %}
{% block content %}{% include "newsletter/content.html" %}{% endblock %}

templates/newsletter/issue_detail_email.html
{% extends "shared/base.html" %}

{% block title %}{% include "newsletter/title.html" %}{% endblock %}
{% block heading %}{% include "newsletter/heading.html" %}{% endblock %}
{% block content %}{% include "newsletter/content.html" %}{% endblock %}

templates/newsletter/issue_list.html
{% extends "shared/object_list.html" %}

{% block title %}Newsletter{% endblock %}
{% block heading %}Newsletter{% endblock %}
{% block object %}
  {% with issue=object %}
    <a href="{{ issue.get_absolute_url }}">
      <b>{{ issue.formatted_number }}</b>
      {% include "shared/published_female.html" with date=issue.end %}
    </a>
  {% endwith %}
{% endblock %}

templates/newsletter/title.html
{{ issue.formatted_title|safe }}